name: Anni
main: net.coasterman10.Annihilation.Annihilation
authors: [coasterman10, stuntguy3000]
version: 1.0
commands:
  annihilation:
    description: Plugin commands for Annihilation
    aliases: anni
  team:
    description: Team command for Annihilation
    aliases: t
  vote:
    description: Places vote for a map
    aliases: v
  stats:
    description: Lists your stats
  class:
    description: Selects your kit
  blue:
    description: Join the Blue team!
  green:
    description: Join the Green team!
  yellow:
    description: Join the Yellow team!
  red:
    description: Join the Red team!