name: Annihilation
main: net.coasterman10.Annihilation.Annihilation
version: 1.0
commands:
  annihilation:
    description: Plugin commands for Annihilation
    aliases: anni
  team:
    description: Team command for Annihilation
  unlock:
    description: Unlocks your locked chest
  vote:
    description: Places vote for a map